# Generated by Django 2.2 on 2021-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description; test test test test test test test test test test test test test test test test test testtest test test test test test'),
            preserve_default=False,
        ),
    ]
