# Generated by Django 2.2 on 2022-01-01 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211231_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
